eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5435/shopping_cart
    username: shopping_cart
    password: shopping_cart
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: false

server:
  port: 8084
  servlet:
    context-path: /catalog
logging:
  level: info
