 eureka:
   instance:
     prefer-ip-address: true
   client:
     serviceUrl:
       defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

 management:
   endpoints:
     web:
       exposure:
         include: hystrix stream

 hystrix:
   dashboard:
     proxy-stream-allow-list: *

 server:
   servlet:
     context-path: /customer
   port: ${SERVER_PORT:8087}
 
 spring:
   application:
     name: customer-service
   datasource:
     url: ${DB_URL:jdbc:postgresql://localhost:5435/shopping_cart?createDatabaseIfNotExist=true}
     username: ${DB_USER:shopping_cart}
     password: ${DB_PASSWORD:shopping_cart}
     driver-class-name: org.postgresql.Driver
   jpa:
     hibernate:
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       ddl-auto: validate
     properties:
       hibernate:
         format_sql: true
         jdbc.lob.non_contextual_creation: true
         temp.use_jdbc_metadata_defaults: false
         synonyms: true
         dialect: org.hibernate.dialect.PostgreSQL10Dialect
         enable_lazy_load_no_trans: true
     show-sql: true
   jmx:
     enabled: false
   liquibase:
     enabled: false
   servlet:
     multipart:
       enabled: true
       max-file-size: ${MULTIPART_MAX_FILE_SIZE:5MB}
       max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:5MB}
       location: ..
 
 logging:
   level:
     org.springframework: INFO
 
