eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: hystrix stream

hystrix:
  dashboard:
    proxy:
     stream:
      allow:
        list: *

zuul:
  routes:
    inventory-service:
      path: /api/**
      service-id: inventory-service
      strip-prefix: false

      inventory-request:
        path: /inventory/request/** #RequiresSomeCheck
        service-id: inventory-request
        #strip-prefix: false
    customer-service:
      path: /customer/**
      service-id: customer-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5435/shopping_cart
    username: shopping_cart
    password: shopping_cart
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: false

io:
  reflectoring:
   kafka:
     bootstrap:
      servers: localhost:9092
        topic-1: CreateTeacherTopic

  logging:
   level:
    org:
     apache:
       kafka: WARN

server:
  port: 8085
  servlet:
    context-path: /inventory
logging:
  level: info
