spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/shopping_cart}
    username: ${DB_USER:shopping_cart}
    password: ${DB_PASSWORD:shopping_cart}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        synonyms: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        enable_lazy_load_no_trans: true
    show-sql: true
  jmx:
    enabled: false
#  liquibase:
#    change-log: classpath:/db/changelog.xml

server:
  port: 8088

logging:
  level:
    org.springframework: INFO
